[package]
name = "rustgames-site"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
tokio = { version = "*", features = ["full"] }
tower-http = { version = "*", features = ["cors"] }